WebAppEmptyMVC5/Controllers/AuthController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebAppEmptyMVC5.Identity;
using WebAppEmptyMVC5.Models.ViewModels;

namespace WebAppEmptyMVC5.Controllers
{
    public class AuthController: Controller
    {
        private AppUserManager _UserManager;

        public AuthController(AppUserManager userMgr)
        {
            _UserManager = userMgr;
        }

        public ActionResult Login(string returnUrl) => View(new LoginModel(returnUrl));

        [HttpPost]
        public async Task<ActionResult> Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _UserManager.FindByNameAsync(model.Name);
                if(user != null)
                {
                    var passwordVerification = _UserManager.PasswordHasher.VerifyHashedPassword(user.PasswordHash, model.Password);
                    if(passwordVerification == PasswordVerificationResult.Success)
                    {
                        var authManager = HttpContext.GetOwinContext().Authentication;
                        var authProps = new AuthenticationProperties { IsPersistent = false };
                        authManager.SignIn(user.GenerateUserIdentity(_UserManager));
                        return Redirect(model.ReturnUrl ?? "/");
                    }
                    else
                    {
                        ModelState.AddModelError(nameof(model.Password), "Incorrect password");
                    }
                }
                else
                {
                    ModelState.AddModelError(nameof(model.Name), "User not found");
                }
            }
            return View(model);
        }

        public ActionResult Logout(string returnUrl)
        {
            HttpContext.GetOwinContext().Authentication.SignOut();
            return Redirect(returnUrl ?? "/");
        }
    }
}

WebAppEmptyMVC5/Controllers/ManageUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebAppEmptyMVC5.Identity;
using WebAppEmptyMVC5.Models.ViewModels;

namespace WebAppEmptyMVC5.Controllers
{
    public class ManageUserController: Controller
    {
        private AppUserManager _UserManager;
        private AppConfig _Cfg;

        public ManageUserController(AppUserManager userManager, AppConfig cfg)
        {
            _UserManager = userManager;
            _Cfg = cfg;
        }

        public ActionResult Register() => View();

        [HttpPost]
        public async Task<ActionResult> Register(UserRegistrationModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new AppUser
                {
                    UserName = model.Name,
                    Email = model.Email,
                    PhoneNumber = model.PhoneNumber
                };
                var validationResult = await _UserManager.UserValidator.ValidateAsync(user);
                if (validationResult.Succeeded)
                {
                    var passwordValidationResult = await _UserManager.PasswordValidator.ValidateAsync(model.Password);
                    if (passwordValidationResult.Succeeded)
                    {
                        user.PasswordHash = _UserManager.PasswordHasher.HashPassword(model.Password);
                        var creationResult = await _UserManager.CreateAsync(user);
                        if (creationResult.Succeeded)
                        {
                            HttpContext.GetOwinContext().Authentication.SignIn(user.GenerateUserIdentity(_UserManager));
                            var emailComfirmationUrl = Url.Action(nameof(ConfirmEmail), new
                            {
                                userName = user.UserName,
                                token = await _UserManager.GenerateEmailConfirmationTokenAsync(user.UserName)
                            });
                            await _UserManager.SendEmailAsync(user.UserName, "Comfirm your registration", $"<a href=\"{emailComfirmationUrl}\">Click me</a>");
                            return Redirect("/");
                        }
                        else
                            PopulateModelErrors(string.Empty, creationResult.Errors);
                    }
                    else
                    {
                        PopulateModelErrors(nameof(model.Password), passwordValidationResult.Errors);
                    }
                }
                else
                {
                    PopulateModelErrors(string.Empty, validationResult.Errors);
                }
            }
            return View(model);
        }

        public async Task<ActionResult> ConfirmEmail(string userName, string token)
        {
            var result = await _UserManager.ConfirmEmailAsync(userName, token);
            return View(result.Errors);
        }

        private void PopulateModelErrors(string property, IEnumerable<string> errors)
        {
            foreach (var error in errors)
                ModelState.AddModelError(property, error);
        }
    }
}

WebAppEmptyMVC5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta encoding="utf-8" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/app.js"></script>
    <link rel="stylesheet" href="~/Styles/shared/bootstrap.css" />
    <link rel="stylesheet" href="~/Styles/shared/bootstrap-grid.css" />
    <link rel="stylesheet" href="~/Styles/shared/bootstrap-reboot.css" />
    @Html.DevExpress().GetStyleSheets(
                new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout, Theme = "Office365" },
                new StyleSheet { ExtensionSuite = ExtensionSuite.Editors, Theme = "Office365" },
                new StyleSheet { ExtensionSuite = ExtensionSuite.GridView, Theme = "Office365" },
                new StyleSheet { ExtensionSuite = ExtensionSuite.RichEdit, Theme = "Office365" },
                new StyleSheet { ExtensionSuite = ExtensionSuite.Spreadsheet, Theme = "Office365" },
                new StyleSheet { ExtensionSuite = ExtensionSuite.HtmlEditor, Theme = "Office365" }
            )
    @Html.DevExpress().GetScripts(
                new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
                new Script { ExtensionSuite = ExtensionSuite.Editors },
                new Script { ExtensionSuite = ExtensionSuite.GridView },
                new Script { ExtensionSuite = ExtensionSuite.RichEdit },
                new Script { ExtensionSuite = ExtensionSuite.Spreadsheet },
                new Script { ExtensionSuite = ExtensionSuite.HtmlEditor }
            )
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Document storage</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    @if (WebAppEmptyMVC5.Helpers.AuthHelper.IsAuthenticated)
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Sign out", "Logout", "Auth", null, new { @class = "nav-link" })
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Sign in", "Login", "Auth", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Register", "Register", "ManageUser", null, new { @class = "nav-link" })
                        </li>
                    }
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
        @RenderBody()
    </div>
</body>
</html>